# Generated by Django 5.0 on 2024-01-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
